//Generated by Azos.Sky.Clients.Tools.SkyGluecCompiler

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

using Azos.Glue;
using Azos.Glue.Protocol;


namespace Azos.Sky.Clients
{
// This implementation needs @Azos.@Sky.@Contracts.@IGDIDAuthorityClient, so
// it can be used with ServiceClientHub class

  ///<summary>
  /// Client for glued contract Azos.Sky.Contracts.IGDIDAuthority server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class GDIDAuthority : ClientEndPoint, @Azos.@Sky.@Contracts.IGdidAuthorityClient
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_AllocateBlock_0;

     //static .ctor
     static GDIDAuthority()
     {
         var t = typeof(@Azos.@Sky.@Contracts.IGdidAuthority);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_AllocateBlock_0 = new MethodSpec(t.GetMethod("AllocateBlock", new Type[]{ typeof(@System.@String), typeof(@System.@String), typeof(@System.@Int32), typeof(@System.@Nullable<@System.@UInt64>) }));
     }
  #endregion

  #region .ctor
     public GDIDAuthority(string node, Binding binding = null) : base(node, binding) { ctor(); }
     public GDIDAuthority(Node node, Binding binding = null) : base(node, binding) { ctor(); }
     public GDIDAuthority(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public GDIDAuthority(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(@Azos.@Sky.@Contracts.IGdidAuthority); }
     }



  #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Azos.Sky.Contracts.IGDIDAuthority.AllocateBlock'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Azos.@Sky.@Contracts.@GDIDBlock' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Azos.@Sky.@Contracts.GdidBlock @AllocateBlock(@System.@String  @scopeName, @System.@String  @sequenceName, @System.@Int32  @blockSize, @System.@Nullable<@System.@UInt64>  @vicinity)
         {
            var call = Async_AllocateBlock(@scopeName, @sequenceName, @blockSize, @vicinity);
            return call.GetValue<@Azos.@Sky.@Contracts.GdidBlock>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Azos.Sky.Contracts.IGDIDAuthority.AllocateBlock'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_AllocateBlock(@System.@String  @scopeName, @System.@String  @sequenceName, @System.@Int32  @blockSize, @System.@Nullable<@System.@UInt64>  @vicinity)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_AllocateBlock_0, false, RemoteInstance, new object[]{@scopeName, @sequenceName, @blockSize, @vicinity});
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
