//Generated by Azos.Sky.Clients.Tools.SkyGluecCompiler

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

using Azos.Glue;
using Azos.Glue.Protocol;


namespace Azos.Sky.Clients
{
// This implementation needs @Azos.@Sky.@Contracts.@ILockerClient, so
// it can be used with ServiceClientHub class

  ///<summary>
  /// Client for glued contract Azos.Sky.Contracts.ILocker server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class Locker : ClientEndPoint, @Azos.@Sky.@Contracts.@ILockerClient
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_ExecuteLockTransaction_0;
     private static MethodSpec @s_ms_EndLockSession_1;

     //static .ctor
     static Locker()
     {
         var t = typeof(@Azos.@Sky.@Contracts.@ILocker);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_ExecuteLockTransaction_0 = new MethodSpec(t.GetMethod("ExecuteLockTransaction", new Type[]{ typeof(@Azos.@Sky.@Locking.@Server.@LockSessionData), typeof(@Azos.@Sky.@Locking.@LockTransaction) }));
         @s_ms_EndLockSession_1 = new MethodSpec(t.GetMethod("EndLockSession", new Type[]{ typeof(@Azos.@Sky.@Locking.@LockSessionID) }));
     }
  #endregion

  #region .ctor
     public Locker(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public Locker(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(@Azos.@Sky.@Contracts.@ILocker); }
     }



  #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Azos.Sky.Contracts.ILocker.ExecuteLockTransaction'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Azos.@Sky.@Locking.@LockTransactionResult' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Azos.@Sky.@Locking.@LockTransactionResult @ExecuteLockTransaction(@Azos.@Sky.@Locking.@Server.@LockSessionData  @session, @Azos.@Sky.@Locking.@LockTransaction  @transaction)
         {
            var call = Async_ExecuteLockTransaction(@session, @transaction);
            return call.GetValue<@Azos.@Sky.@Locking.@LockTransactionResult>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Azos.Sky.Contracts.ILocker.ExecuteLockTransaction'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_ExecuteLockTransaction(@Azos.@Sky.@Locking.@Server.@LockSessionData  @session, @Azos.@Sky.@Locking.@LockTransaction  @transaction)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_ExecuteLockTransaction_0, false, RemoteInstance, new object[]{@session, @transaction});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Azos.Sky.Contracts.ILocker.EndLockSession'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@System.@Boolean' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @System.@Boolean @EndLockSession(@Azos.@Sky.@Locking.@LockSessionID  @sessionID)
         {
            var call = Async_EndLockSession(@sessionID);
            return call.GetValue<@System.@Boolean>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Azos.Sky.Contracts.ILocker.EndLockSession'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_EndLockSession(@Azos.@Sky.@Locking.@LockSessionID  @sessionID)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_EndLockSession_1, false, RemoteInstance, new object[]{@sessionID});
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
