//Generated by Azos.Sky.Clients.Tools.SkyGluecCompiler
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

using Azos.Glue;
using Azos.Glue.Protocol;


namespace Azos.Sky.Clients
{
// This implementation needs @Azos.@Sky.@Contracts.@IRemoteTerminalClient, so
// it can be used with ServiceClientHub class

  ///<summary>
  /// Client for glued contract Azos.Sky.Contracts.IRemoteTerminal server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class RemoteTerminal : ClientEndPoint, @Azos.@Sky.@Contracts.@IRemoteTerminalClient
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_Connect_0;
     private static MethodSpec @s_ms_Execute_1;
     private static MethodSpec @s_ms_Disconnect_2;

     //static .ctor
     static RemoteTerminal()
     {
         var t = typeof(@Azos.@Sky.@Contracts.@IRemoteTerminal);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_Connect_0 = new MethodSpec(t.GetMethod("Connect", new Type[]{ typeof(@System.@String) }));
         @s_ms_Execute_1 = new MethodSpec(t.GetMethod("Execute", new Type[]{ typeof(@System.@String) }));
         @s_ms_Disconnect_2 = new MethodSpec(t.GetMethod("Disconnect", new Type[]{  }));
     }
  #endregion

  #region .ctor
     public RemoteTerminal(string node, Binding binding = null) : base(node, binding) { ctor(); }
     public RemoteTerminal(Node node, Binding binding = null) : base(node, binding) { ctor(); }
     public RemoteTerminal(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public RemoteTerminal(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(@Azos.@Sky.@Contracts.@IRemoteTerminal); }
     }



  #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Azos.Sky.Contracts.IRemoteTerminal.Connect'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Azos.@Sky.@Contracts.@RemoteTerminalInfo' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Azos.@Sky.@Contracts.@RemoteTerminalInfo @Connect(@System.@String  @who)
         {
            var call = Async_Connect(@who);
            return call.GetValue<@Azos.@Sky.@Contracts.@RemoteTerminalInfo>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Azos.Sky.Contracts.IRemoteTerminal.Connect'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_Connect(@System.@String  @who)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_Connect_0, false, RemoteInstance, new object[]{@who});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Azos.Sky.Contracts.IRemoteTerminal.Execute'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@System.@String' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @System.@String @Execute(@System.@String  @command)
         {
            var call = Async_Execute(@command);
            return call.GetValue<@System.@String>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Azos.Sky.Contracts.IRemoteTerminal.Execute'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_Execute(@System.@String  @command)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_Execute_1, false, RemoteInstance, new object[]{@command});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Azos.Sky.Contracts.IRemoteTerminal.Disconnect'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@System.@String' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @System.@String @Disconnect()
         {
            var call = Async_Disconnect();
            return call.GetValue<@System.@String>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Azos.Sky.Contracts.IRemoteTerminal.Disconnect'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_Disconnect()
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_Disconnect_2, false, RemoteInstance, new object[]{});
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
