//Generated by Azos.Sky.Clients.Tools.SkyGluecCompiler

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

using Azos.Glue;
using Azos.Glue.Protocol;


namespace Azos.Sky.Clients
{
// This implementation needs @Azos.@Sky.@Contracts.@ITelemetryReceiverClient, so
// it can be used with ServiceClientHub class

  ///<summary>
  /// Client for glued contract Azos.Sky.Contracts.ITelemetryReceiver server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class TelemetryReceiver : ClientEndPoint, @Azos.@Sky.@Contracts.@ITelemetryReceiverClient
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_SendDatums_0;

     //static .ctor
     static TelemetryReceiver()
     {
         var t = typeof(@Azos.@Sky.@Contracts.@ITelemetryReceiver);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_SendDatums_0 = new MethodSpec(t.GetMethod("SendDatums", new Type[]{ typeof(@Azos.@Instrumentation.@Datum[]) }));
     }
  #endregion

  #region .ctor
     public TelemetryReceiver(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public TelemetryReceiver(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(@Azos.@Sky.@Contracts.@ITelemetryReceiver); }
     }



  #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Azos.Sky.Contracts.ITelemetryReceiver.SendDatums'.
         /// This is a one-way call per contract specification, meaning - the server sends no acknowledgement of this call receipt and
         /// there is no result that server could return back to the caller.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         ///</summary>
         public void @SendDatums(@Azos.@Instrumentation.@Datum[]  @data)
         {
            var call = Async_SendDatums(@data);
            if (call.CallStatus != CallStatus.Dispatched)
                throw new ClientCallException(call.CallStatus, "Call failed: 'TelemetryReceiver.SendDatums'");
         }

         ///<summary>
         /// Asynchronous invoker for  'Azos.Sky.Contracts.ITelemetryReceiver.SendDatums'.
         /// This is a one-way call per contract specification, meaning - the server sends no acknowledgement of this call receipt and
         /// there is no result that server could return back to the caller.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg.
         ///</summary>
         public CallSlot Async_SendDatums(@Azos.@Instrumentation.@Datum[]  @data)
         {
            var request = new @Azos.@Sky.@Contracts.@RequestMsg_ITelemetryReceiver_SendDatums(s_ts_CONTRACT, @s_ms_SendDatums_0, true, RemoteInstance)
            {
               MethodArg_0_data = @data,
            };
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
