SELECT TU.GDID
    , TU.REALM
    , TU.LEVEL
    , TL.LEVEL_DOWN
    , TU.CREATE_UTC
    , TU.START_UTC
    , TU.END_UTC
    , TL.ID
    , TL.PWD
    , TL.START_UTC as LOGIN_START_UTC
    , TL.END_UTC as LOGIN_END_UTC
    , TU.NAME
    , TU.DESCRIPTION
    , TU.PROPS
    , TU.RIGHTS
    , TU.NOTE
FROM tbl_user TU
INNER JOIN tbl_login TL
ON TU.GDID = TL.G_USER
    AND TU.REALM = TL.REALM
WHERE TU.REALM = @realm
    AND TL.ID = @id
    AND TL.TID = @tid
    AND TL.PROVIDER = @provider
;