update tbl_user set
	GDID = @gdid,
	GUID = @guid,
	REALM = @realm,
	NAME = @name,
	LEVEL = @level,
	DESCRIPTION = @description,
	START_UTC = @start_utc,
	END_UTC = @end_utc,
	ORG_UNIT = @org_unit,
	PROPS = @props,
	RIGHTS = @rights,
	NOTE = @note,
	VERSION_UTC = @version_utc,
	VERSION_ORIGIN = @version_origin,
	VERSION_ACTOR = @version_actor,
	VERSION_STATE = @version_state
where GDID = @gdid
AND REALM = @realm