update tbl_login set
  GDID = @gdid,
  REALM = @realm,
  G_USER = @g_user,
  LEVEL_DOWN = @level_down,
  ID = @login_id,
  TID = @tid,
  PROVIDER = @provider,
  PWD = @pwd,
  PROVIDER_DATA = @provider_data,
  START_UTC = @start_utc,
  END_UTC = @end_utc,
  PROPS = @props,
  RIGHTS = @rights,
  VERSION_UTC = @version_utc,
  VERSION_ORIGIN = @version_origin,
  VERSION_ACTOR = @version_actor,
  VERSION_STATE = @version_state
where GDID = @gdid
AND REALM = @realm