// Do not modify by hand. This file is auto-generated by Arow code generator
// Generated on 3/13/2019 6:11:22 PM by Anton at OCTOD
// Framework: [33948984] by Anton@OCTOD:Win32NT on 3/13/2019 10:11:14 PM UTC

using System;
using System.Collections.Generic;
using Azos;
using Azos.IO;
using Azos.Data;
using Azos.Serialization.Arow;
using AW = Azos.Serialization.Arow.Writer;

namespace Azos._arow_generated
{
  ///<summary>
  /// ITypeSerializationCore for Azos.WrappedExceptionData
  ///</summary>
  internal class WrappedExceptionData_arow_core : Azos.Serialization.Arow.ITypeSerializationCore
  {
    void ITypeSerializationCore.Register()
    {
      ArowSerializer.Register(typeof(Azos.WrappedExceptionData), this);
    }

    void ITypeSerializationCore.Serialize(TypedDoc aDoc, WritingStreamer streamer)
    {
      var doc = (Azos.WrappedExceptionData)aDoc;
      // 'tpname' = 111520460468340
      if (doc.TypeName != null)
        AW.Write(streamer, 111520460468340, doc.TypeName);
      else AW.WriteNull(streamer, 111520460468340);
      // 'msg' = 6779757
      if (doc.Message != null)
        AW.Write(streamer, 6779757, doc.Message);
      else AW.WriteNull(streamer, 6779757);
      // 'code' = 1701080931
      AW.Write(streamer, 1701080931, doc.Code);
      // 'src' = 6517363
      if (doc.Source != null)
        AW.Write(streamer, 6517363, doc.Source);
      else AW.WriteNull(streamer, 6517363);
      // 'strace' = 111477511058547
      if (doc.StackTrace != null)
        AW.Write(streamer, 111477511058547, doc.StackTrace);
      else AW.WriteNull(streamer, 111477511058547);
      // 'appname' = 28549237879894113
      if (doc.ApplicationName != null)
        AW.Write(streamer, 28549237879894113, doc.ApplicationName);
      else AW.WriteNull(streamer, 28549237879894113);
      // 'wdata' = 418564367479
      if (doc.WrappedData != null)
        AW.Write(streamer, 418564367479, doc.WrappedData);
      else AW.WriteNull(streamer, 418564367479);
      // 'inner' = 491328007785
      if (doc.InnerException != null)
        Writer.WriteRow(streamer, 491328007785, doc.InnerException);
      else AW.WriteNull(streamer, 491328007785);
    }

    void ITypeSerializationCore.Deserialize(TypedDoc aDoc, ReadingStreamer streamer)
    {
      var doc = (Azos.WrappedExceptionData)aDoc;
      while (true)
      {
        var name = Reader.ReadName(streamer);
        if (name == 0) break;//EODoc
        var dt = Reader.ReadDataType(streamer);
        DataType? atp = null;
        switch (name)
        {
          case 111520460468340:
            { // 'tpname'
              if (dt == DataType.Null) doc.TypeName = null;
              else if (dt == DataType.String) doc.TypeName = Reader.ReadString(streamer);
              else break;
              continue;
            }
          case 6779757:
            { // 'msg'
              if (dt == DataType.Null) doc.Message = null;
              else if (dt == DataType.String) doc.Message = Reader.ReadString(streamer);
              else break;
              continue;
            }
          case 1701080931:
            { // 'code'
              if (dt == DataType.Int32) doc.Code = Reader.ReadInt32(streamer);
              else break;
              continue;
            }
          case 6517363:
            { // 'src'
              if (dt == DataType.Null) doc.Source = null;
              else if (dt == DataType.String) doc.Source = Reader.ReadString(streamer);
              else break;
              continue;
            }
          case 111477511058547:
            { // 'strace'
              if (dt == DataType.Null) doc.StackTrace = null;
              else if (dt == DataType.String) doc.StackTrace = Reader.ReadString(streamer);
              else break;
              continue;
            }
          case 28549237879894113:
            { // 'appname'
              if (dt == DataType.Null) doc.ApplicationName = null;
              else if (dt == DataType.String) doc.ApplicationName = Reader.ReadString(streamer);
              else break;
              continue;
            }
          case 418564367479:
            { // 'wdata'
              if (dt == DataType.Null) doc.WrappedData = null;
              else if (dt == DataType.String) doc.WrappedData = Reader.ReadString(streamer);
              else break;
              continue;
            }
          case 491328007785:
            { // 'inner'
              if (dt == DataType.Null) { doc.InnerException = null; continue; }
              if (dt != DataType.Doc) break;
              var vdoc = new Azos.WrappedExceptionData();
              if (Reader.TryReadRow(doc, vdoc, streamer, CodeGenerator.GetName(name)))
                doc.InnerException = vdoc;
              continue;
            }
        }
        Reader.ConsumeUnmatched(doc, streamer, CodeGenerator.GetName(name), dt, atp);
      }
    }
  }//class

}//namespace

namespace Azos.Log._arow_generated
{
  ///<summary>
  /// ITypeSerializationCore for Azos.Log.Message
  ///</summary>
  internal class Message_arow_core : Azos.Serialization.Arow.ITypeSerializationCore
  {
    void ITypeSerializationCore.Register()
    {
      ArowSerializer.Register(typeof(Azos.Log.Message), this);
    }

    void ITypeSerializationCore.Serialize(TypedDoc aDoc, WritingStreamer streamer)
    {
      var doc = (Azos.Log.Message)aDoc;
      // 'gdid' = 1684628583
      AW.Write(streamer, 1684628583, doc.Gdid);
      // 'guid' = 1684632935
      AW.Write(streamer, 1684632935, doc.Guid);
      // 'rel' = 7103858
      AW.Write(streamer, 7103858, doc.RelatedTo);
      // 'app' = 7368801
      AW.Write(streamer, 7368801, doc.App);
      // 'chnl' = 1819175011
      AW.Write(streamer, 1819175011, doc.Channel);
      // 'tp' = 28788
      Writer.Write(streamer, 28788, (int)doc.Type);
      // 'src' = 6517363
      AW.Write(streamer, 6517363, doc.Source);
      // 'utc' = 6517877
      AW.Write(streamer, 6517877, doc.UTCTimeStamp);
      // 'hst' = 7631720
      if (doc.Host != null)
        AW.Write(streamer, 7631720, doc.Host);
      else AW.WriteNull(streamer, 7631720);
      // 'frm' = 7172710
      if (doc.From != null)
        AW.Write(streamer, 7172710, doc.From);
      else AW.WriteNull(streamer, 7172710);
      // 'top' = 7368564
      if (doc.Topic != null)
        AW.Write(streamer, 7368564, doc.Topic);
      else AW.WriteNull(streamer, 7368564);
      // 'txt' = 7633012
      if (doc.Text != null)
        AW.Write(streamer, 7633012, doc.Text);
      else AW.WriteNull(streamer, 7633012);
      // 'par' = 7496048
      if (doc.Parameters != null)
        AW.Write(streamer, 7496048, doc.Parameters);
      else AW.WriteNull(streamer, 7496048);
      // 'exc' = 6518885
      if (doc.ExceptionData != null)
        Writer.WriteRow(streamer, 6518885, doc.ExceptionData);
      else AW.WriteNull(streamer, 6518885);
      // 'adims' = 495756862561
      if (doc.ArchiveDimensions != null)
        AW.Write(streamer, 495756862561, doc.ArchiveDimensions);
      else AW.WriteNull(streamer, 495756862561);
    }

    void ITypeSerializationCore.Deserialize(TypedDoc aDoc, ReadingStreamer streamer)
    {
      var doc = (Azos.Log.Message)aDoc;
      while (true)
      {
        var name = Reader.ReadName(streamer);
        if (name == 0) break;//EODoc
        var dt = Reader.ReadDataType(streamer);
        DataType? atp = null;
        switch (name)
        {
          case 1684628583:
            { // 'gdid'
              if (dt == DataType.GDID) doc.Gdid = Reader.ReadGDID(streamer);
              else break;
              continue;
            }
          case 1684632935:
            { // 'guid'
              if (dt == DataType.Guid) doc.Guid = Reader.ReadGuid(streamer);
              else break;
              continue;
            }
          case 7103858:
            { // 'rel'
              if (dt == DataType.Guid) doc.RelatedTo = Reader.ReadGuid(streamer);
              else break;
              continue;
            }
          case 7368801:
            { // 'app'
              if (dt == DataType.Atom) doc.App = Reader.ReadAtom(streamer);
              else break;
              continue;
            }
          case 1819175011:
            { // 'chnl'
              if (dt == DataType.Atom) doc.Channel = Reader.ReadAtom(streamer);
              else break;
              continue;
            }
          case 28788:
            { // 'tp'
              if (dt != DataType.Int32) break;
              var ev = (@Azos.@Log.@MessageType)Reader.ReadInt32(streamer);
              doc.Type = ev;
              continue;
            }
          case 6517363:
            { // 'src'
              if (dt == DataType.Int32) doc.Source = Reader.ReadInt32(streamer);
              else break;
              continue;
            }
          case 6517877:
            { // 'utc'
              if (dt == DataType.DateTime) doc.UTCTimeStamp = Reader.ReadDateTime(streamer);
              else break;
              continue;
            }
          case 7631720:
            { // 'hst'
              if (dt == DataType.Null) doc.Host = null;
              else if (dt == DataType.String) doc.Host = Reader.ReadString(streamer);
              else break;
              continue;
            }
          case 7172710:
            { // 'frm'
              if (dt == DataType.Null) doc.From = null;
              else if (dt == DataType.String) doc.From = Reader.ReadString(streamer);
              else break;
              continue;
            }
          case 7368564:
            { // 'top'
              if (dt == DataType.Null) doc.Topic = null;
              else if (dt == DataType.String) doc.Topic = Reader.ReadString(streamer);
              else break;
              continue;
            }
          case 7633012:
            { // 'txt'
              if (dt == DataType.Null) doc.Text = null;
              else if (dt == DataType.String) doc.Text = Reader.ReadString(streamer);
              else break;
              continue;
            }
          case 7496048:
            { // 'par'
              if (dt == DataType.Null) doc.Parameters = null;
              else if (dt == DataType.String) doc.Parameters = Reader.ReadString(streamer);
              else break;
              continue;
            }
          case 6518885:
            { // 'exc'
              if (dt == DataType.Null) { doc.ExceptionData = null; continue; }
              if (dt != DataType.Doc) break;
              var vdoc = new Azos.WrappedExceptionData();
              if (Reader.TryReadRow(doc, vdoc, streamer, CodeGenerator.GetName(name)))
                doc.ExceptionData = vdoc;
              continue;
            }
          case 495756862561:
            { // 'adims'
              if (dt == DataType.Null) doc.ArchiveDimensions = null;
              else if (dt == DataType.String) doc.ArchiveDimensions = Reader.ReadString(streamer);
              else break;
              continue;
            }
        }
        Reader.ConsumeUnmatched(doc, streamer, CodeGenerator.GetName(name), dt, atp);
      }
    }
  }//class

}//namespace


//EOF
