/*<FILE_LICENSE>
 * Azos (A to Z Application Operating System) Framework
 * The A to Z Foundation (a.k.a. Azist) licenses this file to you under the MIT license.
 * See the LICENSE file in the project root for more information.
</FILE_LICENSE>*/
//Generated by Azos.Sky.Clients.Tools.SkyGluecCompiler

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

using Azos.Glue;
using Azos.Glue.Protocol;


namespace Azos.Sky.Clients
{
// This implementation needs @Azos.@Sky.@Contracts.@ITodoQueueClient, so
// it can be used with ServiceClientHub class

  ///<summary>
  /// Client for glued contract Azos.Sky.Contracts.ITodoQueue server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class TodoQueue : ClientEndPoint, @Azos.@Sky.@Contracts.@ITodoQueueClient
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_Enqueue_0;

     //static .ctor
     static TodoQueue()
     {
         var t = typeof(@Azos.@Sky.@Contracts.@ITodoQueue);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_Enqueue_0 = new MethodSpec(t.GetMethod("Enqueue", new Type[]{ typeof(@Azos.@Sky.@Workers.@TodoFrame[]) }));
     }
  #endregion

  #region .ctor
     public TodoQueue(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public TodoQueue(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(@Azos.@Sky.@Contracts.@ITodoQueue); }
     }



  #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Azos.Sky.Contracts.ITodoQueue.Enqueue'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@System.@Int32' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @System.@Int32 @Enqueue(@Azos.@Sky.@Workers.@TodoFrame[]  @todos)
         {
            var call = Async_Enqueue(@todos);
            return call.GetValue<@System.@Int32>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Azos.Sky.Contracts.ITodoQueue.Enqueue'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_Enqueue(@Azos.@Sky.@Workers.@TodoFrame[]  @todos)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_Enqueue_0, false, RemoteInstance, new object[]{@todos});
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
