select
  TU.GDID
  , TU.REALM
  , TU.LEVEL
  , TL.LEVEL_DOWN
  , TU.CREATE_UTC
  , TU.START_UTC
  , TU.END_UTC
  , TL.GDID as G_Login
  , TL.ID
  , TL.PWD
  , TL.START_UTC AS LOGIN_START_UTC
  , TL.END_UTC AS LOGIN_END_UTC
  , TU.ORG_UNIT
  , TU.NAME
  , TU.DESCRIPTION
  , TU.PROPS
  , TU.RIGHTS
  , TL.PROPS AS LOGIN_PROPS
  , TL.RIGHTS AS LOGIN_RIGHTS
  , TU.NOTE
  , TU.VERSION_STATE
  , TL.VERSION_STATE AS LOGIN_VERSION_STATE
  , TU.LOCK_START_UTC
  , TU.LOCK_END_UTC
  , TU.LOCK_ACTOR
  , TU.LOCK_NOTE
  , TL.LOCK_START_UTC as LOGIN_LOCK_START_UTC
  , TL.LOCK_END_UTC as LOGIN_LOCK_END_UTC
  , TL.LOCK_ACTOR as LOGIN_LOCK_ACTOR
  , TL.LOCK_NOTE as LOGIN_LOCK_NOTE
from
  tbl_login TL INNER JOIN tbl_user TU
    ON TL.G_USER = TU.GDID
where
  TL.REALM = @realm
  AND TL.ID = @id
  AND TL.TID = @tid
  AND TL.PROVIDER = @provider
  AND TU.REALM = @realm