drop table TBL_TUPLE;
drop table TBL_FULLGDID;
drop table TBL_TYPES;
drop table TBL_PATIENT;
drop table TBL_DOCTOR;


create table TBL_DOCTOR
(
    COUNTER   NUMBER(19)  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    FIRST_NAME  varchar2(25) not null,
    LAST_NAME   varchar2(25) not null,
    SSN         char(11) not null,
    NPI         char(25) not null,
    DOB      date not null,
    ADDRESS1    varchar2(25),
    ADDRESS2    varchar2(25),
    CITY        varchar2(15),
    STATE       char(2),
    ZIP         char(10),
    PHONE       char(15),
    IS_CERTIFIED char(1),

    YEARS_IN_SERVICE   NUMBER(10),
    AMOUNT             NUMBER(12,4),
    NOTE         LONG,
    PRIMARY KEY (COUNTER),
    CONSTRAINT "SSN" UNIQUE ("SSN")
);


create table TBL_PATIENT
(
  COUNTER   NUMBER(19)  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    FNAME  varchar2(25) not null,
    LNAME   varchar2(25) not null,
    SSN         char(11) not null,
    DOB      date not null,
    ADDRESS1    varchar2(25),
    ADDRESS2    varchar2(25),
    CITY        varchar2(15),
    STATE       char(2),
    ZIP         char(10),
    PHONE       char(15),

    YEARS_IN_SERVICE   NUMBER(10),
    AMOUNT             NUMBER(12,4),
    NOTE         LONG,
    c_doctor     NUMBER(19) references TBL_DOCTOR(COUNTER),
    PRIMARY KEY (COUNTER)
);

create table TBL_TYPES
(
  GDID     NUMBER(19)  GENERATED BY DEFAULT ON NULL AS IDENTITY,

  SCREEN_NAME  char(32) not null,

  STRING_NAME   varchar2(25) not null,
  CHAR_NAME    char(25) not null,

  BOOL_CHAR  char(1),
  BOOL_BOOL  char(1),
  AMOUNT     NUMBER(12,4),
  DOB   date,
  AGE   NUMBER(10),

  PRIMARY KEY (GDID)
);

create table TBL_FULLGDID
(
  GDID        RAW(12) not null,
  VARGDID     RAW(12) not null,
  STRING_NAME   varchar2(25) not null,
  PRIMARY KEY (GDID)
);


create table TBL_TUPLE
(
  COUNTER   NUMBER(19)  not null,
  DATA  varchar2(25) not null,
  PRIMARY KEY (COUNTER)
);