/*<FILE_LICENSE>
 * Azos (A to Z Application Operating System) Framework
 * The A to Z Foundation (a.k.a. Azist) licenses this file to you under the MIT license.
 * See the LICENSE file in the project root for more information.
</FILE_LICENSE>*/

/* Auto generated by Glue Client Compiler tool (gluec)
on 10/10/2018 15:25:11 PM at OCTOD by Zhabis
Do not modify this file by hand if you plan to regenerate this file again by the tool as manual changes will be lost
*/

using System;

using Azos.Glue;
using Azos.Glue.Protocol;


namespace Azos.Instrumentation.Telemetry
{
  ///<summary>
  /// Client for glued contract Azos.Instrumentation.Telemetry.ITelemetryReceiver server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class TelemetryReceiverClient : ClientEndPoint, Azos.Instrumentation.Telemetry.ITelemetryReceiver
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_Send_0;

     //static .ctor
     static TelemetryReceiverClient()
     {
         var t = typeof(Azos.Instrumentation.Telemetry.ITelemetryReceiver);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_Send_0 = new MethodSpec(t.GetMethod("Send", new Type[]{ typeof(@System.@String), typeof(@Azos.@Instrumentation.@Datum) }));
     }
  #endregion

  #region .ctor
     public TelemetryReceiverClient(string node, Binding binding = null) : base(node, binding) { ctor(); }
     public TelemetryReceiverClient(Node node, Binding binding = null) : base(node, binding) { ctor(); }
     public TelemetryReceiverClient(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public TelemetryReceiverClient(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(Azos.Instrumentation.Telemetry.ITelemetryReceiver); }
     }



    #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Azos.Instrumentation.Telemetry.ITelemetryReceiver.Send'.
         /// This is a one-way call per contract specification, meaning - the server sends no acknowledgment of this call receipt and
         /// there is no result that server could return back to the caller.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         ///</summary>
         public void @Send(@System.@String  @siteName, @Azos.@Instrumentation.@Datum  @data)
         {
            var call = Async_Send(@siteName, @data);
            if (call.CallStatus != CallStatus.Dispatched)
                throw new ClientCallException(call.CallStatus, "Call failed: 'TelemetryReceiverClient.Send'");
         }

         ///<summary>
         /// Asynchronous invoker for  'Azos.Instrumentation.Telemetry.ITelemetryReceiver.Send'.
         /// This is a one-way call per contract specification, meaning - the server sends no acknowledgment of this call receipt and
         /// there is no result that server could return back to the caller.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg.
         ///</summary>
         public CallSlot Async_Send(@System.@String  @siteName, Azos.@Instrumentation.@Datum  @data)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_Send_0, true, RemoteInstance, new object[]{@siteName, @data});
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
